print("Super Calculadora!")
A = input("Digite o primeiro valor: ")
B = input("Digite o segundo valor: ")
soma = float(A) + float(B)
print("A soma dos dois valores é: {}".format(soma))
subtração = float(A) - float(B)
print("A subtração de B de A é: {}".format(subtração))
multiplicação = float(A) * float(B)
print("A multiplicação dos dois valores é: {}".format(multiplicação))
divisão = float(A) / float(B)
print("A Divisão de A por B é: {}".format(divisão))